# Model List Column configuration
list: $/logingrupa/biblebuilder/models/book/columns.yaml

# Model Class name
modelClass: Logingrupa\BibleBuilder\Models\Book

# List Title
title: 'logingrupa.biblebuilder::lang.book.list_title'

# Link URL for each record
recordUrl: logingrupa/biblebuilder/books/update/:book_number

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Display filter list
filter: _config_filter.yaml
