<?php
// To add your own short name list go to url  /v4/generate/translation/WEB/table_books/short_name
// replace WEB with database name from what you want to get list of book short book names
// Bible .SQLite3 databases can be downloaded from: https://www.ph4.org/b4_poisk.php
return [
    // This list represents available .SQLite3 databases if folder /storage/BJT.SQLite3
    'bible_translation_database_list' => [
        'BJT', 'BLV', 'MSG', 'NRT', 'NKJV'
    ],
    'bible_translation_settings' => [
        'BJT' => [
            'chapter_language_column' => 'short_name_lv',
            'add_chapter_acronym' => 'true',
        ],
        'BLV' => [
            'chapter_language_column' => 'short_name_lv',
            'add_chapter_acronym' => 'false',
        ],
        'MSG' => [
            'chapter_language_column' => 'short_name_en',
            'add_chapter_acronym' => 'true',
        ],
        'NRT' => [
            'chapter_language_column' => 'short_name_en',
            'add_chapter_acronym' => 'true',
        ],
        'NKJV' => [
            'chapter_language_column' => 'short_name_en',
            'add_chapter_acronym' => 'true',
        ],
    ],
    'bible_translation_chapter_langs' => [
        'BJT' => 'short_name_lv',
        'BLV' => 'short_name_lv',
        'MSG' => 'short_name_en',
        'NRT' => 'short_name_en',
    ],
    'add_chapter_acronyms' => [
        'BJT' => 'true',
        'BLV' => 'false',
        'MSG' => 'true',
        'NRT' => 'true',
    ],
   
    'column_names' => [
        'short_name_lv', 'short_name_ru', 'short_name_en', 
    ],
    'short_name_lv' => [
        '1Moz',
        '2Moz',
        '3Moz',
        '4Moz',
        '5Moz',
        'Joz',
        'Soģ',
        'Rut',
        '1Sam',
        '2Sam',
        '1Ķēn',
        '2Ķēn',
        '1Lai',
        '2Lai',
        'Ezr',
        'Neh',
        'Est',
        'Īja',
        'Psa',
        'Sal.pam',
        'Sal.māc',
        'Aug',
        'Jes',
        'Jer',
        'Rau',
        'Ece',
        'Dan',
        'Hoz',
        'Joe',
        'Amo',
        'Oba',
        'Jon',
        'Mih',
        'Nah',
        'Hab',
        'Cef',
        'Hag',
        'Zah',
        'Mal',
        'Mat',
        'Mar',
        'Lūk',
        'Jāņ',
        'Apu',
        'Rom',
        '1Kor',
        '2Kor',
        'Gal',
        'Efe',
        'Fil',
        'Kol',
        '1Tes',
        '2Tes',
        '1Tim',
        '2Tim',
        'Tit',
        'File',
        'Ebr',
        'Jēk',
        '1Pēt',
        '2Pēt',
        '1Jāņ',
        '2Jāņ',
        '3Jāņ',
        'Jūd',
        'Atkl',
        // 'Tob',
        // 'Jud',
        // 'EstS',
        // '1Mak',
        // '2Mak',
        // '3Mak',
        // '4Mak',
        // 'Sāl',
        // 'Sīr',
        // 'Bar',
        // 'JerV',
        // 'Zuza',
        // 'Azar',
        // 'Bēls',
        // 'Mans',
        // '2Ezr',
        // '3Ezr',
    ],
    'short_name_en' => [
                    'Gen',
                    'Exo',
                    'Lev',
                    'Num',
                    'Deu',
                    'Josh',
                    'Judg',
                    'Ruth',
                    '1Sam',
                    '2Sam',
                    '1Kin',
                    '2Kin',
                    '1Chr',
                    '2Chr',
                    'Ezr',
                    'Neh',
                    'Esth',
                    'Job',
                    'Ps',
                    'Prov',
                    'Eccl',
                    'Song',
                    'Isa',
                    'Jer',
                    'Lam',
                    'Ezek',
                    'Dan',
                    'Hos',
                    'Joel',
                    'Am',
                    'Oba',
                    'Jona',
                    'Mic',
                    'Nah',
                    'Hab',
                    'Zeph',
                    'Hag',
                    'Zech',
                    'Mal',
                    'Mat',
                    'Mar',
                    'Luk',
                    'John',
                    'Acts',
                    'Rom',
                    '1Cor',
                    '2Cor',
                    'Gal',
                    'Eph',
                    'Phil',
                    'Col',
                    '1Ths',
                    '2Ths',
                    '1Tim',
                    '2Tim',
                    'Tit',
                    'Phlm',
                    'Heb',
                    'Jam',
                    '1Pet',
                    '2Pet',
                    '1Jn',
                    '2Jn',
                    '3Jn',
                    'Jud',
                    'Rev',
    ],
    'short_name_ru' => [
                    'Быт',
                    'Исх',
                    'Лев',
                    'Чис',
                    'Втор',
                    'Нав',
                    'Суд',
                    'Руфь',
                    '1Цар',
                    '2Цар',
                    '3Цар',
                    '4Цар',
                    '1Пар',
                    '2Пар',
                    '1Езд',
                    'Неем',
                    'Есф',
                    'Иов',
                    'Пс',
                    'Прит',
                    'Еккл',
                    'Песн',
                    'Ис',
                    'Иер',
                    'Плач',
                    'Иез',
                    'Дан',
                    'Ос',
                    'Иоил',
                    'Ам',
                    'Авд',
                    'Ион',
                    'Мих',
                    'Наум',
                    'Авв',
                    'Соф',
                    'Агг',
                    'Зах',
                    'Мал',
                    'Мат',
                    'Мар',
                    'Лук',
                    'Ин',
                    'Деян',
                    'Рим',
                    '1Кор',
                    '2Кор',
                    'Гал',
                    'Еф',
                    'Флп',
                    'Кол',
                    '1Фес',
                    '2Фес',
                    '1Тим',
                    '2Тим',
                    'Тит',
                    'Флм',
                    'Евр',
                    'Иак',
                    '1Пет',
                    '2Пет',
                    '1Ин',
                    '2Ин',
                    '3Ин',
                    'Иуд',
                    'Откр',
    ],

];
